#!/bin/sh
 
#### Torque directives:
 
# Give the job a name.
#PBS -N neorl_example
 
# Use the default queue.
#PBS -q default
 
# Request 2 nodes and 12 processors per node.
#PBS -l nodes=2:ppn=12
 
# Request 72 hour max walltime to run this job.
#PBS -l walltime=72:00:00
#PBS -j oe 

 
#### Set the working directory and path.
 
# This cd command tells Torque to execute your code in the same directory that
# you submitted the job in.  So if the input files for your code are in
# /home/bob/openmc_sims/sim5, make sure you cd into that directory before
# running qsub.
cd $PBS_O_WORKDIR
 
# This command will tell Torque to use the same PATH that you were using when
# you ran qsub.  It's commented out because it is not necessary in this case,
# but you may need to uncomment it to get your code to run right.
#PATH=$PBS_O_PATH
 
 
#### Run the simulation.

export PATH="/home/radaideh/anaconda3/bin:$PATH"
alias neorl="python3 /home/radaideh/neorl/neorl.py -i"
export PYTHONPATH=/home/radaideh/anaconda3/lib/python3.7/site-packages
 
neorl ex1-10x10-train.inp
